<#
#̷\   ⼕龱ᗪ㠪⼕闩丂ㄒ龱尺 ᗪ㠪ᐯ㠪㇄龱尸爪㠪𝓝ㄒ
#̷\   🇵​​​​​🇴​​​​​🇼​​​​​🇪​​​​​🇷​​​​​🇸​​​​​🇭​​​​​🇪​​​​​🇱​​​​​🇱​​​​​ 🇸​​​​​🇨​​​​​🇷​​​​​🇮​​​​​🇵​​​​​🇹​​​​​ 🇧​​​​​🇾​​​​​ 🇨​​​​​🇴​​​​​🇩​​​​​🇪​​​​​🇨​​​​​🇦​​​​​🇸​​​​​🇹​​​​​🇴​​​​​🇷​​​​​@🇮​​​​​🇨​​​​​🇱​​​​​🇴​​​​​🇺​​​​​🇩​​​​​.🇨​​​​​🇴​​​​​🇲​​​​​
#̷\ 
#̷\   Manifest File Generated on Tue, 28 Dec 2021 04:36:32 GMT
#̷\   Current Git Revision a91cf727c5daf4b412eae72ba3bb96c41b2fc31f   
#>


@{

    ModuleVersion     = '1.0.2'

    RootModule        = 'PowerShell.Module.Shim'

    GUID              = 'a6a69dd3-fc9d-46d0-8359-c70ccbe4ca24'

    CompanyName       = 'Unknown'

    Author            = 'Guillaume Plante'

    Copyright         = '(c) 2020 Guillaume Plante. All rights reserved.'

    Description       = ''

    PowerShellVersion = '5.0'

    RequiredAssemblies = @()

    # Private data to pass to the module specified in RootModule. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{
        PSData = @{
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags       = @('PowerShell.Module.Shim')
            # A URL to the license for this module.
            LicenseUri = 'https://github.com/codecastor/PowerShell.Module.Shim/blob/main/COPYING'
            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/codecastor/PowerShell.Module.Shim'
        } # End of PSData hashtable
    } # End of PrivateData hashtable


#̷\  ===================================================
#̷\     ＭＯＤＵＬＥ ＥＸＰＯＲＴＥＤ ＦＵＮＣＴＩＯＮＳ
#̷\  ===================================================

	# !NOTE! --- The following functions declaration was automatically generated by the build script. ---
	FunctionsToExport = @(

		# --- Exported Functions from Shims.ps1 ---
		"Get-ShimGenExePath",
		"Initialize-Shim",
		"Repair-AllShims",
		"New-Shim")
	

#̷\  ===================================================
#̷\     ＴＨＥ ＬＩＳＴ ＯＦ ＥＸＰＯＲＴＥＤ ＡＬＩＡＳＥＳ
#̷\  ===================================================

	# !NOTE! --- The following alias declaration was automatically generated by the build script. ---
	# List of all aliases packaged with this module

	AliasesToExport = @()

#̷\  ===================================================
#̷\     ＴＨＥ ＬＩＳＴ ＯＦ ＦＩＬＥＳ 
#̷\ （ＩＦ ＣＯＭＰＲＥＳＳＥＤ， ＷＩＬＬ ＢＥ ＥＭＰＴＹ）
#̷\  ===================================================

	FileList = @()

}




